name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  claude-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v40
      with:
        files: |
          **/*.java
          **/*.xml
          **/*.md
    
    - name: Claude Code Review
      if: steps.changed-files.outputs.any_changed == 'true'
      uses: actions/github-script@v7
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      with:
        script: |
          const { execSync } = require('child_process');
          
          // Get the diff
          const diff = execSync('git diff origin/${{ github.base_ref }}..HEAD', { encoding: 'utf8' });
          
          // Prepare the review prompt
          const reviewPrompt = `
          Please review this Java code changes for:
          1. Code quality and best practices
          2. Potential bugs or issues
          3. Security vulnerabilities
          4. Performance improvements
          5. Documentation completeness
          
          Here's the diff:
          \`\`\`diff
          ${diff}
          \`\`\`
          
          Please provide constructive feedback in markdown format.
          `;
          
          // Create temp file for the request payload to avoid shell quoting issues
          const fs = require('fs');
          const requestPayload = {
            model: "claude-3-5-sonnet-20241022",
            max_tokens: 2000,
            messages: [
              {
                role: "user",
                content: reviewPrompt
              }
            ]
          };
          
          fs.writeFileSync('/tmp/claude_request.json', JSON.stringify(requestPayload));
          
          try {
            const response = execSync(`curl -s -X POST https://api.anthropic.com/v1/messages \\
              -H "Content-Type: application/json" \\
              -H "x-api-key: $ANTHROPIC_API_KEY" \\
              -H "anthropic-version: 2023-06-01" \\
              -d @/tmp/claude_request.json`, { encoding: 'utf8' });
            
            console.log('Claude API Response:', response);
            const claudeResponse = JSON.parse(response);
            
            if (!claudeResponse.content || !claudeResponse.content[0]) {
              throw new Error('Invalid response format: ' + JSON.stringify(claudeResponse));
            }
            
            const reviewContent = claudeResponse.content[0].text;
            
            // Post review as PR comment
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## 🤖 Claude AI Code Review\n\n${reviewContent}\n\n---\n*Review generated by Claude AI*`
            });
          } catch (error) {
            console.error('Error calling Claude API:', error);
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## ❌ Claude AI Code Review Failed\n\nUnable to generate code review. Please check the ANTHROPIC_API_KEY secret configuration.`
            });
          }